### ISSUE TITLE
How does the tags relate to the installed awx-operator version?

### ISSUE THREAD

**Issue by gsg-git** [GiuffreLab/awx-operator#5]
Hello!

Im new to awx and got my enwiroment running thanks to your git.
I leaned that the Tags in the kustomize file relate to the versions of the awx-operator installed, but how?
The numbers arent the same of the web gui and not awx-operator and the link doesnt seem to lead anything you could use with a regular browser - so im a litte confused.

Could you tell me more?
So i could propably enter the right numers in the furture when the next updates appear.

Thank you very much in advance!

**Comment by GiuffreLab** [comment]
AWX-Operator has all of the manifest configuration items to build AWX, that Repo is the one who's versions you need to match in your Kustomize.yaml file.

So the upgrade process would be to change the version of AWX-Operator in the two lines of the Kustomize.yaml file, and then re-apply to upgrade.

As an example.. This shows AWX-Operator version `2.11.0` which deploys AWX version `23.7.0`

``` shell
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.11.0
  - awx-manifest.yaml

  # Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.11.0

  # Specify a custom namespace in which to install AWX
namespace: awx
```

To upgrade it to the latest version you would alter the two lines to the current version of `2.12.2` to deploy AWX version `23.9.0`

``` shell
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.12.2
  - awx-manifest.yaml

  # Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.12.2

  # Specify a custom namespace in which to install AWX
namespace: awx
```

Then run your apply command to update the version

``` shell
kubectl apply -k .
```

Then you can watch the pods terminate, and rebuild as the new version over the next few minutes.

**Comment by gsg-git** [comment]
Okay i just have to change the config and just reappy?
i took a part of the official guide where you have to delete everything gelated to the operator and the reappy everything again.
and i thought the kustomize command and the kubectl apply would be necessary.
I will test your tip!
And how do i see the version of the awx operator - the ones in tried seem to get me wrong ones and the web /chatgpt ifind is not useful.

**Comment by gsg-git** [comment]
I got it my mistake:
I used
`kubectl describe deployment awx-operator -n awx`
And just looked at the first image version which was wrong:
wrong row:
` Image:      gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
`
right row:
`Image:      quay.io/ansible/awx-operator:2.12.2
`

**Comment by gsg-git** [comment]
Thank you @GiuffreLab !
I tested the patching with just the file edit and reapplying with
`kubectl apply -k .`
And i patched the vm within minutes.
The webservice took a little while longer than usual - made me a little nervous 
Now everything is fine!
Thank you!
