### ISSUE TITLE
Question ssh keys

### ISSUE THREAD

**Issue by gsg-git** [GiuffreLab/awx-operator#6]
Hello Again!
I need for my setup an integrated pub key.
Can i proceed like in the kustomization guide?
i want to install a [collection ](https://github.com/ansible-collections/community.general)via playbook locally, but no key no connection.

Thank you again!

**Comment by GiuffreLab** [comment]
You want to set up a Public Key to do what exactly? Connect to a host machine? You would create a machine credential and copy the private key in the SSH keys field. You then need to copy that keys public key to the machine you want to connect to.

**Comment by GiuffreLab** [comment]
Makes sense. There are plenty of examples out there on how to, I have one in a repo as well.
