### ISSUE TITLE
question about ansible builder and setup with kustomize

### ISSUE THREAD

**Issue by gsg-git** [GiuffreLab/awx-operator#7]
Hello!
I like to add a custom ee for community.general.rocketchat module from here:
https://github.com/ansible-collections/community.general
and the guides use ansible builder and deploy this with docker or podman
https://www.linkedin.com/pulse/creating-custom-ee-awx-phil-griffiths/?trk=public_profile_article_view
is the execution enviromen an own container/pod then?
How can i add this into Kubernetes with your installation?

Thank you very much again!!

**Comment by GiuffreLab** [comment]
https://github.com/GiuffreLab/building-execution-environments

**Comment by gsg-git** [comment]
very good - you make me happy everywhere and explain stuff simple that i get it without being for years involven with awx kubernetes etc. 
Do these execution enviroments update everythime i update the awx with  kubectl apply -k . too? or do they have som kind of versioning which could be a problem when i dont update the custom execution enviroment?

**Comment by GiuffreLab** [comment]
Execution environments are independent of AWX in that they get hosted somewhere (docker hub, or quay as an example) as container images. When you add them to AWX you can select the option to pull the Execution environment image every time you run a Template that uses it as one example.

This allows you to update your Execution Environment without having to update your AWX instance.

**Comment by gsg-git** [comment]
okay cool i found a [collection ](https://quay.io/repository/andreichnla/awx-ee?tab=tags&tag=latest)with a lot preinstalled with my wanted one too so i dont have to build myself.

**Comment by GiuffreLab** [comment]
This is the one I host on Docker Hub.

https://hub.docker.com/r/giuffrelab/awx-community-general-ee

**Comment by gsg-git** [comment]
OKay thank you i used your container.
I thought there would be another container in docker ,but the ee just is connected to the container image and will executed when necessary?
i thought it would be more complicated.
Now i just have to test.
Im just curious if i set the ee for a template if the default features of the defauilt ee still would be aviable?
![grafik](https://github.com/GiuffreLab/awx-operator/assets/92863111/846a943c-5ed8-4878-8005-00263fa15427)

**Comment by gsg-git** [comment]
I really learned a fuckin lot from you - and you dont loose the will to explain propably basic stuff to a noob like me!

**Comment by GiuffreLab** [comment]
You would still have the default EE available to choose for a template job, however you can only select one to use at a time. I keep what is available in mine listed in the writeup for it on docker hub, and It should contain the standard default EE's collections, plus what I add.

**Comment by gsg-git** [comment]
Yeah i can send messages with rochetchat via your ee - its good that you write  the content of it down - its really exemplary what all schoud do, but almost noone did...
The other EE i foud was described as  "almost everything included"

**Comment by GiuffreLab** [comment]
I've just updated it to version 17 (I do monthly version updates).

**Comment by gsg-git** [comment]
Yeah i can send messages with rochetchat via your ee - its good that you write  the content of it down - its really exemplary what all schoud do, but almost noone did...
The other EE i foud was described as  "almost everything included" 
do you know inf community.crypto.openssh_keypair is in your EE?
